# Generated by Django 5.2.3 on 2025-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_birth_date_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('student', 'Ученик'), ('trainer', 'Тренер'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='guest', max_length=10),
        ),
    ]
